// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is generated by the CampusOS Plugin CLI Installer.

import { initFrontend as initCalendar } from '@plugins/calendar/frontend/init';
import { initFrontend as initClub } from '@plugins/club/frontend/init';
import { initFrontend as initEvent } from '@plugins/event/frontend/init';
import { initFrontend as initTask } from '@plugins/task/frontend/init';
import { initFrontend as initVendor } from '@plugins/vendor/frontend/init';

export function initializePlugins() {
  if (typeof window !== 'undefined') {
    // Prevent double initialization in React strict mode / fast refresh
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    if ((window as any).__pluginsInitialized) return;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (window as any).__pluginsInitialized = true;
  }

  // Initialize all known frontend plugin UI components
  initCalendar();
  initClub();
  initEvent();
  initTask();
  initVendor();
}
