import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import AdmZip from 'adm-zip';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PLUGINS_DIR = path.join(__dirname, '../plugins');
const REGISTRY_FILE = path.join(__dirname, '../frontend/lib/plugins/init.ts');

function generateRegistry() {
  console.log('🔄 Generating frontend plugin registry...');

  if (!fs.existsSync(PLUGINS_DIR)) {
    console.warn('⚠️  No plugins directory found.');
    return;
  }

  const plugins = fs
    .readdirSync(PLUGINS_DIR, { withFileTypes: true })
    .filter((dirent) => dirent.isDirectory())
    .map((dirent) => dirent.name);

  const activePlugins = [];

  for (const plugin of plugins) {
    const initTsPath = path.join(PLUGINS_DIR, plugin, 'frontend', 'init.ts');
    const initTsxPath = path.join(PLUGINS_DIR, plugin, 'frontend', 'init.tsx');
    const initJsPath = path.join(PLUGINS_DIR, plugin, 'frontend', 'init.js');

    if (
      fs.existsSync(initTsPath) ||
      fs.existsSync(initTsxPath) ||
      fs.existsSync(initJsPath)
    ) {
      activePlugins.push({
        name: plugin,
        // Capitalize and format for safe variable name
        varName: `init${plugin.charAt(0).toUpperCase() + plugin.slice(1).replace(/[^a-zA-Z0-9]/g, '')}`
      });
    }
  }

  const imports = activePlugins
    .map(
      (p) =>
        `import { initFrontend as ${p.varName} } from '@plugins/${p.name}/frontend/init';`
    )
    .join('\n');
  const initializers = activePlugins.map((p) => `  ${p.varName}();`).join('\n');

  const registryContent = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is generated by the CampusOS Plugin CLI Installer.

${imports}

export function initializePlugins() {
  if (typeof window !== 'undefined') {
    // Prevent double initialization in React strict mode / fast refresh
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    if ((window as any).__pluginsInitialized) return;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (window as any).__pluginsInitialized = true;
  }

  // Initialize all known frontend plugin UI components
${initializers}
}
`;

  fs.writeFileSync(REGISTRY_FILE, registryContent, 'utf8');
  console.log(
    `✅ Registry updated successfully. Wired up ${activePlugins.length} frontend plugin(s).`
  );
}

function installPlugin(sourcePath) {
  if (!sourcePath) {
    console.error('❌ Error: Please provide a source path (.zip or folder).');
    process.exit(1);
  }

  const absoluteSource = path.resolve(sourcePath);
  if (!fs.existsSync(absoluteSource)) {
    console.error(`❌ Error: Source path not found: ${absoluteSource}`);
    process.exit(1);
  }

  const stat = fs.statSync(absoluteSource);
  let pluginName = '';

  if (!fs.existsSync(PLUGINS_DIR)) {
    fs.mkdirSync(PLUGINS_DIR, { recursive: true });
  }

  if (stat.isFile() && absoluteSource.endsWith('.zip')) {
    console.log(`📦 Extracting zip archive: ${sourcePath}...`);
    const zip = new AdmZip(absoluteSource);
    // Determine plugin name from zip structure or plugin.json inside zip
    const zipEntries = zip.getEntries();

    let manifestEntry = zipEntries.find(
      (e) =>
        e.entryName === 'plugin.json' || e.entryName.endsWith('/plugin.json')
    );
    if (!manifestEntry) {
      console.error(
        '❌ Error: Invalid plugin. No plugin.json found in the zip archive.'
      );
      process.exit(1);
    }

    const manifestContent = zip.readAsText(manifestEntry);
    try {
      const manifest = JSON.parse(manifestContent);
      pluginName = manifest.name;
    } catch (e) {
      console.error('❌ Error: plugin.json is invalid JSON.');
      process.exit(1);
    }

    if (!pluginName) {
      console.error('❌ Error: plugin.json must have a "name" field.');
      process.exit(1);
    }

    const targetDir = path.join(PLUGINS_DIR, pluginName);
    if (fs.existsSync(targetDir)) {
      console.error(
        `❌ Error: Plugin directory already exists at ${targetDir}. Please uninstall it first.`
      );
      process.exit(1);
    }

    // Extract exactly the folder containing plugin.json to targetDir
    // If zip is packaged like "myplugin/plugin.json", we extract the contents of "myplugin"
    const basePath = manifestEntry.entryName.replace('plugin.json', '');

    fs.mkdirSync(targetDir, { recursive: true });

    zipEntries.forEach((entry) => {
      if (entry.entryName.startsWith(basePath) && !entry.isDirectory) {
        const relativePath = entry.entryName.substring(basePath.length);
        const destPath = path.join(targetDir, relativePath);
        fs.mkdirSync(path.dirname(destPath), { recursive: true });
        fs.writeFileSync(destPath, entry.getData());
      }
    });
  } else if (stat.isDirectory()) {
    console.log(`📦 Copying plugin directory: ${sourcePath}...`);
    const manifestPath = path.join(absoluteSource, 'plugin.json');
    if (!fs.existsSync(manifestPath)) {
      console.error(
        '❌ Error: Invalid plugin directory. No plugin.json found.'
      );
      process.exit(1);
    }

    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    pluginName = manifest.name;

    if (!pluginName) {
      console.error('❌ Error: plugin.json must have a "name" field.');
      process.exit(1);
    }

    const targetDir = path.join(PLUGINS_DIR, pluginName);
    if (fs.existsSync(targetDir)) {
      console.error(
        `❌ Error: Plugin directory already exists at ${targetDir}. Please uninstall it first.`
      );
      process.exit(1);
    }

    // Node.js fs.cpSync is available in v16.7+
    fs.cpSync(absoluteSource, targetDir, { recursive: true });
  } else {
    console.error('❌ Error: Source path must be a directory or a .zip file.');
    process.exit(1);
  }

  console.log(`✅ Plugin "${pluginName}" installed successfully!`);
  generateRegistry();
}

function uninstallPlugin(pluginName) {
  if (!pluginName) {
    console.error(
      '❌ Error: Please provide the name of the plugin to uninstall.'
    );
    process.exit(1);
  }

  const targetDir = path.join(PLUGINS_DIR, pluginName);
  if (!fs.existsSync(targetDir)) {
    console.error(`❌ Error: Plugin "${pluginName}" is not installed.`);
    process.exit(1);
  }

  console.log(`🗑️  Uninstalling plugin "${pluginName}"...`);
  fs.rmSync(targetDir, { recursive: true, force: true });

  console.log(`✅ Plugin "${pluginName}" uninstalled successfully!`);
  generateRegistry();
}

const args = process.argv.slice(2);
const command = args[0];

switch (command) {
  case 'install':
    installPlugin(args[1]);
    break;
  case 'uninstall':
    uninstallPlugin(args[1]);
    break;
  case 'generate-registry':
    generateRegistry();
    break;
  default:
    console.log(`
CampusOS Plugin CLI
-------------------
Usage:
  node scripts/plugin.js install <path-to-folder-or-zip>
  node scripts/plugin.js uninstall <plugin-name>
  node scripts/plugin.js generate-registry
`);
    process.exit(1);
}
